FROM pandoc/latex:latest

WORKDIR /app

RUN apk add --no-cache git bash grep python3

RUN git config --global core.quotepath false
ENV LANG=ja_JP.UTF-8
ENV LC_ALL=ja_JP.UTF-8

ENTRYPOINT ["/bin/bash", "-c"]

CMD ["scripts/update.sh"]